- CoreWiki/Pages/Create.cshtml
- CoreWiki/Pages/Delete.cshtml
- CoreWiki/Pages/Edit.cshtml
- CoreWiki/Pages/LatestChanges.cshtml
- CoreWiki/Pages/_Layout.cshtml
- README.md
We idea is to show in the readme page:
- List the related streams
- List the features implemented
- List the lessons learned
> README.MD -  Initial Description

- CoreWiki/Pages/Create.cshtml
- CoreWiki/Pages/Delete.cshtml
- CoreWiki/Pages/Edit.cshtml
- CoreWiki/Pages/LatestChanges.cshtml
- CoreWiki/Pages/_Layout.cshtml
Create.cshtml
- Back to List --> Back to Home
- asp-page="Index" --> asp-page="./Details"
Delete.cshtml
- Include field Topic in screen
- Back to Home Page --> Back to Home
Edit.cshtml
- Back to List --> Back to Home
LatestChanges.cshtml
- Create New --> New article
_Layout.cshtml
- Remove Home menu
- Create Page --> New article
> Cosmetic Changes

- CoreWiki/Pages/_Layout.cshtml
Updates `_layout.cshtml` as it only appears to have half of the required automation changes in it.
Library files are referencing the wrong CDN versions and/or not pointing to wwwroot/lib properly
> Fix _layout.cshtml

- CoreWiki/Helpers/UrlHelpers.cs
Fix issue #56  by updating the new code to strip any unwanted characters rather than returning to the old method from StackOverflow.
> Fix urlhelper issue #56

- CoreWiki/Pages/All.cshtml
- CoreWiki/Pages/All.cshtml.cs
Resubmitted #47 to avoid conflicts appearing due to the age of the Pull Request.
This is one method of selecting the page size utilising a cookie and some JavaScript. This could also be placed in a user profile, but the project doesn't support that yet.
It contains updated versions of the files All.cs.html and All.cs from that pull request.
> Page Selector using a cookie and JavaScript

- CoreWiki/Pages/_ValidationScriptsPartial.cshtml
was missing the "dist" folder in the filename - see issue #52
> fix error loading jquery.validate.unobtrusive.js

- CoreWiki/Pages/Components/ListComments/ListComments.cshtml
- CoreWiki/TagHelpers/GravatarTagHelper.cs
ADD: #65 Avatar for comments should come from Gravatar
FIX: #66 Avatar from comments is always the same image
```
```
> Adding TagHelper for Gravatar

- CoreWiki/Pages/Details.cshtml
> set details page title to article topic

- CoreWiki/Pages/Create.cshtml
- CoreWiki/Pages/Edit.cshtml
- CoreWiki/Pages/_EditorScript.cshtml
This is PR to implement #34
Few issues are still open.
Should we only allowe only .md / .markdown files to be uploaded?
Should multiple file uplaod be supported?
BUG:
If big file is uploaded part of the text is not visible until click inside field.
> (WIP) Import markwdown files

- CoreWiki/CoreWiki.csproj
With this PR we intend to adjust the references of the project, as reported in the issue (**#80 Microsoft.AspNetCore.App metapackage for ASP.NET Core 2.1**)
> Update project references (ASP.Net Core 2.1)

- CoreWiki/Pages/Edit.cshtml.cs
The @nmalocic was the first to identify the problem in edit functionality and reported it in the issue (#75 Edit is not working) and PR (#76 Fixed issues related to edit page). The issue is still open status despite the @csharpfritz have already done even merge.
This PR tries to solve the problem when editing/saving an article. The source of the problem was in one of the previous merges to which part of the code was lost.
> Fix Edit/Save continues not working

- CoreWiki/Pages/Shared/_Layout.cshtml
- CoreWiki/Pages/Shared/_LoginPartial.cshtml
> Fixes Menubar (#87)

- CoreWiki/Pages/Shared/_Layout.cshtml
During the merge of a newer PR the following lines overwrote my previous edits.
https://github.com/csharpfritz/CoreWiki/blob/587e6d2f6aa074fa867bbb15e4289225247e858a/CoreWiki/Pages/Shared/_Layout.cshtml#L82-L84
> Fixed Copyright layout class bug

- CoreWiki/Pages/All.cshtml
- CoreWiki/Pages/All.cshtml.cs
- CoreWiki/Pages/_ArticleRow.cshtml
- CoreWiki/wwwroot/css/themeDark.css
Changed Page size from 2 to 10 in order to take advantage of the grid UI
> Enhanced All Artticles Page Articles

- CoreWiki/Helpers/ArticleHelpers.cs
- CoreWiki/Helpers/StringHelpers.cs
- CoreWiki/Helpers/UrlHelpers.cs
- CoreWiki/Pages/Create.cshtml.cs
- CoreWiki/Pages/CreateArticleFromLink.cshtml
- CoreWiki/Pages/CreateArticleFromLink.cshtml.cs
- CoreWiki/Pages/Edit.cshtml.cs
This PR is an attempt to address #79. The main goal is to be able to use the existing Markdown syntax used to create links, as a way to automate the creation of stub articles when those links do not refer to articles that already exist in the wiki.
The screenshot below shows a test article with 2 links to articles that do not yet exist (highlighted in yellow), one to a link that does exist (home-page) and another to an external website (DuckDuckGo) - underlined in red:
Clicking 'Save' with these two unresolved links in place brings up the following page:
Selecting 'Yes' on this page creates the stub articles and returns the user to the page their created or edited:
Viewing All Articles shows the new stub articles have been created, and are ready to be edited:
I am sure that there are …
> Added creation of new stub articles from links embedded in an Article

- CoreWiki.Test/CoreWiki.Test.csproj
- CoreWiki.Test/Helpers/StringHelperTests.cs
- CoreWiki.sln
- CoreWiki/Helpers/StringHelpers.cs
Could be fairly inefficient because of the allocations, but it passes all current test cases.
Might want to include "words" that consist of digits only? Thoughts?
Fixes #111
> Start testing some things and fix word count helper

- CoreWiki/Areas/Identity/Pages/Account/ConfirmEmail.cshtml.cs
> Fix for #128: Redirect in ConfirmEmail.cshtml.cs file

- CoreWiki/Helpers/AriaHelper.cs
- CoreWiki/TagHelpers/PagerTagHelper.cs
Just a snippet to help with implementing accessibility features for screenreaders and such.
> Improve support for screenreaders on paginator links

- CoreWiki/CoreWiki.csproj
- CoreWiki/Helpers/StringHelpers.cs
- CoreWiki/Pages/Search.cshtml
https://github.com/Humanizr/Humanizer
> Use the Humanizer package for pluralization (and other features) rather than rolling our own

- CoreWiki/Areas/Identity/Data/CoreWikiUser.cs
- CoreWiki/Areas/Identity/Pages/Account/Manage/Index.cshtml
- CoreWiki/Areas/Identity/Pages/Account/Manage/Index.cshtml.cs
- CoreWiki/Areas/Identity/Pages/Account/Register.cshtml
- CoreWiki/Areas/Identity/Pages/Account/Register.cshtml.cs
- CoreWiki/Pages/Details.cshtml.cs
For #127 - GDPR concerns. Added a CanNotify flag to the CoreWiki User so that users can opt-in (and subsequently opt-out) of receiving notifications from the application. I an no UI person, so some styling required if someone wants to do it.
> Add CanNotify flag to CoreWiki user for GDPR #127

- CoreWiki/Areas/Identity/Pages/Account/Register.cshtml
Wrapped the checkbox in a form group so it has margin-bottom by default. See:
https://getbootstrap.com/docs/4.1/components/forms/#form-groups
> updated checkbox on register.cshtml

- CoreWiki/TagHelpers/PagerTagHelper.cs
- Created a single function for creating clickable or non-clickable links `CreatePaginatorButton`
- Rearranged code for cleaner look
> Fixed aria links for paginator after merge

- contributing.md
Cribbed from a few open source projects, lays out how to do a PR
using rebase to keep everything nice and clean.
Closes #72
> Update contributing.md with Pull Request steps.

- CoreWiki/Configuration/AppSettings.cs
- CoreWiki/CoreWiki.csproj
- CoreWiki/Pages/Shared/_ThemePartial.cshtml
- CoreWiki/Pages/_ViewImports.cshtml
- CoreWiki/Program.cs
- CoreWiki/Startup.cs
- CoreWiki/appsettings.json
- CoreWiki/web.config
Helps to prevent: 
- Reflective XSS
- IFrame clickjacking
- Information leakage (server type, powered by, referer)
- Prevent content [MIME sniffing](https://www.keycdn.com/support/what-is-mime-sniffing/)
When CSP is implemented it will prevent unsafe inline scripts and styles (such as the unsafe style in #144)
> Add some security headers and prepare for CSP implementation

- CoreWiki/TagHelpers/PagerTagHelper.cs
> Fixed paginator logic errors

- .travis.yml
- Dockerfile
- build.cake
- build.ps1
- build.sh
Changes
* Upgrade Cake to 0.28.1
* Execute tests
* Updated travis to SDK 2.1.301
CI
* Linux build - https://travis-ci.org/devlead/CoreWiki/jobs/399632437
* Mac build- https://travis-ci.org/devlead/CoreWiki/jobs/399632438
* Windows - https://ci.appveyor.com/project/devlead/corewiki/build/1.0.11
* Docker  - https://hub.docker.com/r/devlead/corewiki/builds/bl29fmczf2zfme5bvnypprr/
> Update Cake & run tests

- CoreWiki/Pages/Create.cshtml.cs
- CoreWiki/Pages/Edit.cshtml.cs
* Fixes cases where the slug is returned as blank
* Topic should not be converted to lower case before being _sluggified_ (causes missing hyphens in slug)
E.g. (HomePage became homepage instead of home-page)
Fixes Issue where HomePage slug was renamed to homepage instead of home-page
Fixed #147 
Fixed #148
> Slug fixes
