CoreWiki/Pages/All.cshtml, CoreWiki/Pages/All.cshtml.cs, CoreWiki/Pages/_Layout.cshtml, CoreWiki/TagHelpers/PagerTagHelper.cs
Updates the TagHelper to use the TagBuilder class when making the html nodes. 
- Uses TagBuilder
- This always provides well-created nodes
- Use `IHtmlGenerator.GeneratePageLink()` to create the anchor tag instead. This is what the AnchorTagHelper uses. 
- Fixes html node logic (no ending `</li>` tags)
- Adds summary comments so that you get helper documentation when composing the `<pager>`  tag in a smart editor (like VS)
- Adds `asp-page` as a parameter to the `PagerTagHelper`
- This replaces the hard-coded `./All` but should never have to be used with the current page. In fact I can't think of a reason to have it, but I left it in anyway to show where it goes in the GeneratePageLink.
Instead of passing `PageNumber` through the `querystring` it is now passed through the route (a better …
=> Pager TagHelper update

CoreWiki/Pages/_Layout.cshtml, CoreWiki/package.json
We're using a CDN to point to the production Bootstrap js, so we need to update every time the package changes. One of the downsides of using CDNs
=> Upgrade package.json and _Layout.cshtml to point to Bootstrap 4.1.1

CoreWiki/Pages/All.cshtml
links were not using the new seo urls & new int id's
=> fixed links to the details, edit & delete pages

.gitignore, .travis.yml, Dockerfile, appveyor.yml, build.cake, build.ps1, build.sh
Currently there seems to be no continuous integration hooked up for this projects, this proposes AppVeyor, Travis CI and Docker hub all orchestrated through the same Cake build script for minimal duplication of build logic. End goal is to have each commit and PR build automatically on multiple environments and operating systems with ease.
I've Divided PR into 4 commits
1. Adds Cake build script and powershell / bash boostrappers to fetch and execute Cake (bootstrappers currently assume .NET CLI present, but SDK installation could be added in bootstrappers too)
2. Adds AppVeyor yaml file, which instructs how do build the project on AppVeyor (which basically means it should just be a matter for repo/forks of adding project to AppVeyor and it should build)
3. Adds a Docker file, multistage …
=> Adds Cake & Docker build script, AppVeyor & Travis CI configuration

CoreWiki/Helpers/ArticleNotFoundResult.cs, CoreWiki/Pages/ArticleNotFound.cshtml, CoreWiki/Pages/Details.cshtml.cs, CoreWiki/Pages/Edit.cshtml.cs, CoreWiki/Pages/HttpErrors/404.cshtml, CoreWiki/Startup.cs
This PR aims to implement the wiki page not found issue https://github.com/csharpfritz/CoreWiki/issues/13
I've intentionally created two error pages. The first is for when the URL is a missing article slug (e.g `/a-non-existing-article`). This will show the 'Article not found' error page. The other 404 error page is is for more generic 404s (e.g `/some/url/that-does/not/exist`).
I would be grateful for any feedback, specifically:
- Any changes to the text in the 404 pages
- Is the `ArticleNotFound` ViewResult class a good approach? And should it be in the `CoreWiki.Helpers` namespace or elsewhere?
P.S @csharpfritz my apologies for my first two PRs (the tabs and editorconfig) today. I was apprehensive about committing a PR to the project and I thought a small code tidy (e.g the boy scout …
=> 'Article not found' and 'Page not found' error pages (Issue 13)

CoreWiki/Helpers/StringHelpers.cs, CoreWiki/Pages/All.cshtml, CoreWiki/Pages/LatestChanges.cshtml, CoreWiki/Pages/Search.cshtml, CoreWiki/Pages/Search.cshtml.cs, CoreWiki/Pages/_ArticleRow.cshtml, CoreWiki/Pages/_Layout.cshtml, CoreWiki/SearchEngines/ArticlesDbSearchEngine.cs, CoreWiki/SearchEngines/IArticlesSearchEngine.cs, CoreWiki/SearchEngines/SearchResult.cs, CoreWiki/Startup.cs, CoreWiki/TagHelpers/PagerTagHelper.cs
This PR aims to make a basic search engine for CoreWiki (Issue https://github.com/csharpfritz/CoreWiki/issues/3) that can be used as a foundation for more advanced search functionality later on.
My current search functionality is **VERY** basic. It simply does a case-insensitive search on the database to see if either the topic or content contains the query. Ordering is just by the Article view count DESC. I've implemented a `IArticlesSearchEngine` interface so it should be fairly easy to one day swap this basic search with something more advanced like ElasticSearch or Azure Search.
I also refactored the Article row from the All Articles page into a partial to keep the search page DRY. 
**Please note I've make a small UI tweak:** the Article row for 'All Articles' and the Article row for …
=> Basic search functionality (Issue 3)

CoreWiki/Areas/Identity/Pages/Account/Logout.cshtml.cs
I think the template code isn't handling the redirect of the route that exists in the project Startup.cs
*  Made the design decision to return to "/" instead
=> Fix Logout

CoreWiki/Pages/Shared/_ThemePartial.cshtml
This works by placing a cookie to represent the theme on the users machine. 
It uses cookies rather than identity because you may want different themes on different devices (like a phone)
Place ```<partial name="_ThemePartial" />``` wherever you want the selector
=> _ThemePartial to implement Light and Dark themes

CoreWiki/CoreWiki.csproj, CoreWiki/Pages/Details.cshtml, CoreWiki/Pages/Shared/_CommentsPartial.cshtml, CoreWiki/Pages/Shared/_DisqusComments.cshtml, CoreWiki/Pages/Shared/_Layout.cshtml, CoreWiki/appsettings.json
The fix for #93 was to remove the leading '.'
The 'Theme' select element will now respond to the size of the screen more accurately; When the screen is too small it will move to a new row and resize to fill the row.
I added an option for #67 Disqus as the comments engine for the Wiki.
To enable Disqus, complete the following checklist:
=> Fixed #93 and also fixed the styles for the _ThemePartial. Introduce Disqus as a comments option closing #67

CoreWiki/Helpers/StringHelpers.cs, CoreWiki/Pages/Details.cshtml, CoreWiki/Pages/_ViewImports.cshtml
I refactored the [CalculateReadTime](https://github.com/csharpfritz/CoreWiki/blob/aad16b0d78c8ea245896cd89c7c5dcdf61fbfa96/CoreWiki/Pages/Details.cshtml#L14) function to StringHelpers and instead of returning a calculated amount of minutes it returns a TimeSpan. I then use the milliseconds from the TimeSpan and moment.js' duration method to give a better representation of the total time it would take to read the article.
=> Updated estimated read time to use moment.js

.gitignore, CoreWiki/Areas/Identity/Data/CoreWikiIdentityContext.cs, CoreWiki/Areas/Identity/IdentityHostingStartup.cs, CoreWiki/Startup.cs
On a fresh clone and run, the application requires IdentityMigrations ran on it, which could be an issue if the application is deployed somewhere. Instead of requiring a manual migration, we should seed the DB with the schema for Identity. Doing this will create a wikiIdentity.db file per the HostingStartup done per #86. I also added Microsoft social authentication, but whoever wants it will need to follow this
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins
=> Added Seeder for IdentityDB

CoreWiki/Properties/launchSettings.json
I've run into this issue several times on other ASP.NET Core projects.
Maybe an earlier version of the SDK scaffolded a project with the `launchSettings.json` using an invalid port for IIS Express?
In any case, according to https://github.com/aspnet/Home/issues/2308 this must be true for HTTPS to work with IIS Express
```
IIS Express HTTPS port must be in the range 44300-44399
```
The `sslPort` was set to `5001` which causes binding to fail when running the site behind IIS Express and debugging out of Visual Studio.
I changed it to `44333` and now you can press the green play button in VS for the `IIS Express` profile and everything launches and runs correctly.
=> fix(launchSettings): set sslPort to valid port for IIS Express

.gitignore, .vscode/launch.json, .vscode/tasks.json
The .gitignore of the project was set to ignore the `.vscode` directory where vscode keeps its workspace settings.
While it is correct to ignore the `.vs` directory created by Visual Studio, the `.vscode` directory contains shared workspace configuration.
You can add a list of recommended extensions, formatting/tooling configuration you want everyone to share and, in the case of this PR, the pre-configured launch settings for debugging the ASP.NET Core app.
Including these settings in the repo could help a new dev on the project from accidentally mis-configuring their settings and having trouble debugging.
=> build(vscode): workspace/launch settings

CoreWiki/Pages/Components/ListComments/ListComments.cshtml
It is better to say "are" here, because the subject of the sentence "There are no  **comments** to show!" is plural.
=> Replaced use of the word 'is' with 'are'

CoreWiki/CoreWiki.csproj, CoreWiki/Pages/Shared/_Layout.cshtml, CoreWiki/Startup.cs
For #12 - Following on from the work to add a `manifest.json` file and wonderful icons, by @sgwatgit, I added Mads Kristensen's `WebEssentials.AspNetCore.PWA` nuget package to the project. Following this implementation, running the project in Chrome shows that we have a service worker running.
See [this](https://github.com/madskristensen/WebEssentials.AspNetCore.ServiceWorker) page for details and further configuration options.
=> Added Mads Kristensen's PWA nuget pkg

CoreWiki/Pages/Delete.cshtml.cs, CoreWiki/Pages/Edit.cshtml.cs, CoreWiki/Pages/_ArticleRow.cshtml, CoreWiki/Startup.cs
The 'Edit' and 'Delete' routes will now work with /{Slug}/Edit and /{Slug}/Delete instead of /Edit?id={id} and /Delete?id={id}.
=> Enhanced page routes to satisfy 'Change route definition (#27)'

CoreWiki/CoreWiki.csproj
Updated the following packages:
- Application Insights to 2.3.0
- Snickler.RSSCore to 1.0.3
Trivial PR I know, but I want to work on #79 and did these updates to my fork of CoreWiki. In the spirit of a PR having as few commits as possible, I have submitted this one in anticipation of a future PR to address #79.
=> Updated App Insights and Snickler nuget packages

CoreWiki/Areas/Identity/AuthorizationPolicy.cs, CoreWiki/Pages/Delete.cshtml, CoreWiki/Pages/_ArticleRow.cshtml, CoreWiki/TagHelpers/AuthorizationTagHelper.cs
This new tag helper will allow you to use two of three new attributes on an HTML element. These attributes will either hide or add a `title` attribute with a customized message. By default the `title` attribute will tell the user that they do not have permission to complete the action.
The `asp-policy` attribute will tell the tag helper which policies the user must have.
The `asp-policy-message` attribute will create the `title` attribute on the HTML element.
The `asp-policy-hidden` attribute will hide the HTML element if the user doesn't have the policies required.
=> Added an Authorization tag helper

CoreWiki/TagHelpers/PagerTagHelper.cs
- Starts to address #113 
- Added a property to the pager tag that sets maximum pages to display. (Defaults to 10)
- Adds first, previous, next and last navigation buttons
- Active link stays as close to the middle of the paginator as possible if there are lots of articles on either side.
Example showing two `<pager>` tags on the All documents page, with one set to 10 max links and the other set to 5 max links displayed.
=> Enhanced paginator

CoreWiki/Pages/Components/CreateComments/CreateComments.cshtml, CoreWiki/Pages/Create.cshtml, CoreWiki/Pages/CreateArticleFromLink.cshtml, CoreWiki/Pages/Delete.cshtml, CoreWiki/Pages/Edit.cshtml
- The buttons on the Add & Edit pages blended into the upload control.
- Bootstrap doesn't have a "btn-default" class, swap for "btn-outline-primary" which is used elsewhere in the site.
=> Make buttons uniform across the site.

CoreWiki/Properties/launchSettings.json
On OSX, `dotnet run` can fail with "port in use". Port 5000 is used by
Apple Time Capsule, Port 5001 used by some VPN software (e.g. Cisco
AnyConnect)
=> Change ports for dev server

CoreWiki.Test/Helpers/UrlHelperTests.cs, CoreWiki/Helpers/UrlHelpers.cs, CoreWiki/Pages/ArticleNotFound.cshtml, CoreWiki/Pages/Create.cshtml.cs, CoreWiki/Pages/Details.cshtml.cs, CoreWiki/Pages/Shared/_Layout.cshtml, CoreWiki/Startup.cs
404 page contains a create link.  Create get() modified to check if
the slug exists or not.  If it does, redirect to the Edit page.  If
it does not, show the Create page with the Topic pre-filled with an
attempt to "de-slugify" it.
Closes #135, #122
=> Allow creation of Article from 404 page.

CoreWiki/Migrations/20180624223112_AddSlugHistory.Designer.cs, CoreWiki/Migrations/20180624223112_AddSlugHistory.cs, CoreWiki/Models/ApplicationDbContext.cs, CoreWiki/Models/SlugHistory.cs, CoreWiki/Pages/Details.cshtml.cs, CoreWiki/Pages/Edit.cshtml, CoreWiki/Pages/Edit.cshtml.cs
We don't want existing links to be broken so if the Topic of an Article
is changed, which means the Slug has changed, record the old Slug so
we can look it up and do a 302 if an Article request would normally 404.
Closes #121 though does it in a different way.  I wasn't a fan of an article having a permanent slug so `<site>/no` could land on a page where the Topic is "yes".  Doing it this way, if the Slug changes from `no` to `yes` then `<site>/no` 302s to `<site>/yes` where the Topic is "yes".  Somebody can then come along and create a proper `<site>/no` page.
The one unhandled situation is SlugHistory table could grow large over time and should be trimmed periodically if another Article has taken over the Slug.
=> Add ability to change a Topic

CoreWiki/CoreWiki.csproj, CoreWiki/Pages/_ViewImports.cshtml, CoreWiki/TagHelpers/MarkdownTagHelper.cs
Fixes #144 
Creating this as a TagHelper means we should be protected where ever we use the `<markdown>` tag, without any additional work. This replaces the Westwind TagHelper but still runs the output through that pipeline with some additional steps for encoding and sanitising
Encoding process is as follows:
* Encode HTML elements using HttpUtility
* Send through normal Westwind Markdig parsing pipeline
* Sanitize output using HtmlSanitizer
I think we loose some markdown features such as custom tags.
I have tested basic XSS against this, and checked several markdown syntax' aren't affected.
More extensive testing of affected markdown features required.
=> MarkdownTagHelper to Encode, Parse and Sanitize

CoreWiki/Configuration/AppSettings.cs, CoreWiki/EmailTemplates/NewComment.tmpl, CoreWiki/Pages/Details.cshtml.cs, CoreWiki/Services/EmailMessageFormatter.cs, CoreWiki/Services/EmailNotifier.cs, CoreWiki/Services/IEmailMessageFormatter.cs, CoreWiki/Services/IEmailNotifier.cs, CoreWiki/Services/INotificationService.cs, CoreWiki/Services/ITemplateParser.cs, CoreWiki/Services/ITemplateProvider.cs, CoreWiki/Services/NotificationService.cs, CoreWiki/Services/TemplateParser.cs, CoreWiki/Services/TemplateProvider.cs, CoreWiki/Startup.cs, CoreWiki/appsettings.json
Issue #149
Adding a basic email templating service and email sender to send notification emails, expending on the work already done by Jeff and Amanda. 
In this pull request only 'new comment' notifications are sent but can easily be extended to send email verification emails.
The email template is very basic and could do with a little love and attention.
```json
{
"EmailNotifications": {
"SendGridApiKey": "",
"FromEmailAddress": "noreply@corewiki.jeffreyfritz.com",
"FromName": "No Reply Team"
}
```
Added multiple new services:
* ```ITemplateProvider```: Reads template files from disk (EmailTemplates directory).
* ```ITemplateParser```: Replaces template placeholders with data from a model.
* ```IEmailMessageFormatter```: Uses ```ITemplateProvider``` and ```ITemplateParser``` to create a …
=> Expended on email notification feature and added email templates, closes #149

CoreWiki/Pages/All.cshtml
A regression was introduced in commit [c371aca](https://github.com/csharpfritz/CoreWiki/commit/c371acae0a200980bf3351a6078f45353ea4208e). The `All.cshtml` page needs an opening `<script>` tag 👍
=> Fix missing `<script>` tag

CoreWiki.Test/CoreWiki.Test.csproj, CoreWiki/CoreWiki.csproj
I updated to the latest nuget packages and checked with the `dotnet outdated` global tool to know whether we have all latest versions everywhere in the project.
the global tool dotnet-outdated can be found at [https://github.com/jerriep/dotnet-outdated](https://github.com/jerriep/dotnet-outdated) and works in a similar way as `npm outdated`.
=> Updated to latest nuget packages

README.md
Twitch [automatically deletes](https://help.twitch.tv/customer/portal/articles/1575302-videos-on-demand#managing) past broadcasts after a set amount of time, and this leaves old links broken.
I replaced all old twitch VOD urls with their equivalent YouTube counterparts.
In addition, I have added all the links in which Jeff is working on CoreWiki up to date with timestamps.
=> Update README recordings list
